[[references-for-michael-j.-pedersen]]
References for Michael J. Pedersen
----------------------------------

Arnaud Viviers::
  President, OrcaTec, LLC +
  arnaud.viviers@orcatec.com, 770-650-7706x227

ifdef::web[]
Brian Holcomb::
  Coworker at OrcaTec, LLC +
  bcholcomb@yahoo.com, 770-639-2681
endif::web[]
Dan Drown::
  Manager at Datapipe, Inc. +
  misterbawb@gmail.com
Greg Mirsky::
  Coworker at Weight Watchers +
  gmirsky@gmail.com, 516-695-6321
Herb Roitblat::
  Manager at OrcaTec, LLC +
  herb@orcatec.com, 805-815-7395
Jason Donahue::
  Coworker at Datapipe +
  jdonahue@timekiller.org
Jordan Clauberg::
  Coworker at 6th Avenue Electronics +
  jordanclauberg@yahoo.com, 973-580-0842
Kristin Waychoff::
  Manager at 6th Ave Electronics +
  kristin.waychoff@gmail.com, 908-377-7601
Nick Loadholtes::
  Coworker at OrcaTec, LLC +
  nloadholtes@gmail.com, 404-579-2070
Ohad Imer::
  Manager at Weight Watchers +
  917-679-5040
Phil Merrifield::
  Coworker at Weight Watchers +
  Pmerrifield@Gmail.com, 646-589-1336
Quin Gregor::
  Part owner of OrcaTec, LLC +
  quin@sandrose.net, 770-722-6514

