Resume: Michael J. Pedersen
===========================
:author: Michael J. Pedersen
:date: October 31, 2014

[[summary]]
ifdef::web[]
Summary
-------

I'm a DevOps Engineer with over 12 years of experience managing
http://windows.microsoft.com/en-US/windows/home[Windows], Linux, UNIX, and Macintosh systems. This means that I look at
the whole picture, not just System Administration or Software Development. Shepherding a system through the creation and
deployment process, and seeing the customer pleasure at having things work the way they need it to, is a particular joy
of mine. Making people's lives better is the point of technology, after all.

I am comfortable in a wide range of working conditions. Work environments have been heterogeneous
(http://windows.microsoft.com/en-US/windows/home[Windows], OSX, and several flavors of Linux), small to medium sized
(from 10 to 120 servers, 20 to 300 workstations), and mixed locations (all local to all remote teams).
endif::web[]
ifndef::web[]
-------------------------
 Michael J. Pedersen 
 42 Henry St 
 Oxford, NJ 07863 
 <m.pedersen@icelus.org>
 (908) 718-1337
-------------------------

== Executive Summary ==

ifdef::dev[]
Developer with over 12 years of experience writing software in multiple different languages. A strong focus on Web development, especially writing software to connect systems. Work environments have been heterogeneous (http://windows.microsoft.com/en-US/windows/home[Windows], OSX, and several flavors of Linux/UNIX), and mixed locations (all local to all remote teams).
endif::dev[]
ifndef::dev[]
DevOps Engineer with over 12 years of experience managing http://windows.microsoft.com/en-US/windows/home[Windows], Linux/UNIX, and OSX. Strong focus on automation. Work environments have been heterogeneous (http://windows.microsoft.com/en-US/windows/home[Windows], OSX, and several flavors of Linux/UNIX), small to medium sized (10-120 servers, 20-300 workstations), and mixed locations (all local to all remote teams).
endif::dev[]

endif::web[]

[[job-history]]
Job History
-----------

[[weight-watchers---systems-engineering-lead]]
Weight Watchers - Systems Engineering Lead
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

New York City, NY - 2014-2015
ifdef::web[]

Weight Watchers is a Fortune 500 company focused on helping customers manage their weight and reduce health problems
caused by it.

My role was focused on providing internal support within the company to enable other groups to support the customer
base.

endif::web[]
ifdef::dev[]
 * Developed lightweight monitoring tool for use within my group.
endif::dev[]
ifdef::ops[]
 * Configured http://www.vormetric.com/[Vormetric] products to ensure
http://en.wikipedia.org/wiki/Health_Insurance_Portability_and_Accountability_Act[HIPAA] compliance for customer data.
 * Worked to transfer from http://www.rackspace.com/cloud[Rackspace Cloud] to http://www.openstack.org/[Openstack] based
private cloud.
endif::ops[]

[[orcatec-llc---developer]]
OrcaTec, LLC - Developer
~~~~~~~~~~~~~~~~~~~~~~~~

Atlanta, GA (Telecommute) - 2012-2014
ifdef::web[]

OrcaTec is in the litigation support industry (they help their clients reduce the costs of being sued). OrcaTec is
primarily a software-as-a-service company, allowing OrcaTec to host customer data. While working here, my focus has been
on improving the GUI. This has involved refactoring code heavily, adding new features, and adding new tests to cover
existing and new code.

The team structure at OrcaTec is geographically very diverse. In addition to my own telecommuting, I have teammates in
many states. We all work remotely, and we all work together to make the product the best that it can be.

endif::web[]
ifdef::dev[]
* Developed advanced search tool using http://www.python.org/[Python], http://www.turbogears.org/[TurboGears], and
http://www.jquery.com/[jQuery].
* Created new document production framework from scratch.
* Spearheaded conversion from http://yui.github.io/yui2/[YUI 2] to http://www.jquery.com/[jQuery] and
http://www.jqueryui.com/[jQueryUI].
* Reduced multi-hour http://www.sqlalchemy.org/[SQLAlchemy] bulk database jobs to minutes.
* Found major security hole (remote code execution) and closed it.
endif::dev[]
ifdef::ops[]
* Debugged and resolved memory issues that were causing systems to shut down.
* Incorporated memcached into our stack to handle sessions and cached data.
* Installed and configured http://wso2.com/products/identity-server[WSO2 Identity Server] for our
http://www.openid.net/[OpenID] implementation
* Switched web server from http://www.pythonpaste.org/[Paster] to http://httpd.apache.org/[Apache] with
https://code.google.com/p/modwsgi/[mod_wsgi].
endif::ops[]
ifdef::web[]
* Documented internal server API, wrote a http://www.python.org/[Python] class to standardize it's use.
* Added tag cloud (using https://github.com/indyarmy/jQuery.awesomeCloud.plugin[awesomecloud plugin for jQuery]).
* Corrected Unicode handling errors in the code.
* Added holds and matters framework, allowing customers to state that documents belonging to specific cases and should
not be deleted while the cases are ongoing.
* Created a tool to allow copying settings between instances.
* Added support for allowing customers to login using http://www.openid.net/[OpenID].
* Added user preferences to the frontend.
* Resolved intermittent issue with drag/drop events that had been unsolvable by the existing team.
* Implemented login idle timeout functionality.
* Identified weaknesses in the database model, and added code to prevent those weaknesses from being hit.
* Wrote http://www.python.org/[Python] framework to manage long running background jobs.
* Refactored http://www.python.org/[Python] and JavaScript code on a regular basis to reduce code repetition and
increase legibility.
* Mentored other developers in the use of http://www.turbogears.org/[TurboGears],
http://www.sqlalchemy.org/[SQLAlchemy], http://www.python.org/[Python], and JavaScript.
* Organized weekly meetings for members of the frontend (OTGUI) team, providing a chance to discuss (in depth) the
issues the team was facing.
endif::web[]

[[choopa.com---developer]]
Choopa.com - Developer
~~~~~~~~~~~~~~~~~~~~~~

Sayreville, NJ - 2012
ifdef::web[]

As a developer at Constant.com (renamed from Choopa.com in Jan, 2012), I worked with a variety of technologies, with the
heaviest focus being on http://www.openstack.org/[OpenStack] and http://www.nagios.org/[Nagios]. I helped bring two
products to production level availability for their customers (specifically: the Dedicated Cloud Server and Backup
systems).

endif::web[]
ifdef::dev[]
* Developed library to manage http://www.openstack.org/[OpenStack] nodes, and gather billing information.
* Built http://www.nagios.org/[Nagios] configuration file generator for in-house web interface for
http://www.nagios.org/[Nagios].
endif::dev[]
ifdef::ops[]
* Configured http://www.bacula.org/[Bacula] backup system as replacement for custom backup scripts.
* Reconfigured http://www.nagios.org/[Nagios] monitoring, reducing full check from 8 hours to 2 minutes.
endif::ops[]
ifdef::web[]
* Refactored in-house http://www.nagios.org/[Nagios] web interface. This reduced the workload from six files down to one
when adding new checks.
* Several smaller bug fixes and features throughout the internal code base.
endif::web[]

[[th-avenue-electronics---systems-administrator-devops-engineer]]
6th Avenue Electronics - Systems Administrator, DevOps Engineer
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Springfield, NJ - 2005-2008, 2011
ifdef::web[]

In 2007, 6th Avenue began switching from their then-current POS system (named http://www.tylernet.com/[Tyler]) to
http://www.sap.com/[SAP]. At the end of 2010, http://www.sap.com/[SAP] was declared unworkable, and the effort was begun
to switch back to http://www.tylernet.com/[Tyler].

The environment at 6th Avenue covered a wide range of platforms spread out over 120 servers (both physical and virtual).
We had http://www.vmware.com/[VMware] ESX, http://windows.microsoft.com/en-US/windows/home[Windows] Server 2003,
http://windows.microsoft.com/en-US/windows/home[Windows] Server 2008, http://www.centos.org/[CentOS] Linux,
http://www.suse.com/[Suse] Linux, and http://www.debian.org/[Debian] GNU/Linux. In 2011, I was brought back to
transition the point of sale system and become the IT Manager. At the time the point of sale transition was completed,
we had a team of 6 people managing the servers and about 300 desktops.

endif::web[]
ifdef::dev[]
* Successfully lead migration from http://www.sap.com/[SAP] to http://www.tylernet.com/[Tyler] Point of Sale system.
* Developed http://www.python.org/[Python] validation scripts for data going from http://www.sap.com/[SAP] into
http://www.tylernet.com/[Tyler].
* Automated configuration options within http://www.tylernet.com/[Tyler] that could not be done via import.
* Developed http://www.python.org/[Python] program to copy sales data from http://www.tylernet.com/[Tyler] POS to
http://www.postgresql.org/[PostgreSQL].
endif::dev[]
ifdef::ops[]
* Installed and configured http://www.zenoss.org/[Zenoss] for full systems monitoring.
* Implemented http://www.vmware.com/[VMware] Virtual Infrastructure 3.
* Maintained http://www.tylernet.com/[Tyler] POS/ERP system on
http://www8.hp.com/us/en/products/servers/hp-ux.html[HP-UX] (and, later, Linux).
* Maintained Active Directory, including implementation of group policy.
endif::ops[]
ifdef::web[]
* Wrote scripts to satisfy company needs using https://www.autoitscript.com/site/autoit/[AutoIt3] and
http://www.python.org/[Python].
* Wrote automated installer for the http://www.tylernet.com/[Tyler] client program to incorporate the program plus the
mandatory pieces that we needed.
* Developed workaround to resolve issue in point of sales system causing store wide sales terminal lockups.
* Maintained heterogeneous environment (>60 Linux, >40 http://windows.microsoft.com/en-US/windows/home[Windows]
servers).
* Implemented ticket tracking system for help desk issues.
* Deployed http://technet.microsoft.com/en-us/windowsserver/bb332157.aspx[Windows Software Update Server] for Microsoft
product updates.
* Updated customer facing web site to reflect changes to NJ sales tax rates.
* Exported data from http://www.tylernet.com/[Tyler] point of sale system for import into http://www.sap.com/[SAP]
system.
* Created an internal wiki for use by the IT department, including populating with over 30 pages of documentation at
time of deployment.
* Wrote several scripts to extract data from http://www.tylernet.com/[Tyler] POS system before
http://www.postgresql.org/[PostgreSQL] database was available.
* Maintained http://www.commvault.com/[CommVault] backup system and disaster recovery site.
* Developed intranet pages (using AJAX) to allow customer service representatives to find old invoices in the database
copy of http://www.tylernet.com/[Tyler]'s data.
* Created intranet pages (using AJAX) to assist in the selling of complex systems.
* Retrieved bulk information from http://www.tylernet.com/[Tyler] point of sale system for audits.
* Performed field certification of http://mapdb.sap.com/[MaxDB] system for http://www.commvault.com/[CommVault],
providing reliable and supported backups for http://www.sap.com/[SAP] databases.
* Configured all servers for newly implemented http://www.sap.com/[SAP] system.
* Spearheaded server room cleanup: Shut down over 30 servers, removed over a mile of wire.
* Rack mounted, installed, and prepared newly arrived servers for use in projects.
endif::web[]

[[datapipe-inc.---unix-developer]]
Datapipe, Inc. - UNIX Developer
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Jersey City, NJ - 2008-2011
ifdef::web[]

Datapipe manages thousands of customers servers. Many of these servers are connected to various shared storage systems,
including http://www.3par.com/[3Par], http://www.isilon.com/[Isilon], and backup servers. Datapipe required an ability
to do reporting on what data was being stored on these systems for each client, and then report that data back to
billing. In addition, Datapipe required monitoring of the backup systems to ensure timely and complete backups of client
data. My duties primarily focused on making these systems work well.

My team structure is worth describing briefly as well: My immediate manager worked out of Austin, TX. One coworker
worked in the same building as myself, and I had two "extended" teammates who worked in Jersey City, NJ (I worked in
Somerset, NJ). The extended team included the http://windows.microsoft.com/en-US/windows/home[Windows] developers, while
I was on the UNIX development team.

endif::web[]
ifdef::dev[]
* Created reporting system called StorageWeb (using http://www.turbogears.org/[TurboGears]), enabling new revenue
stream.
* Developed http://www.python.org/[Python] app named unixops, allows server access via one time
http://www.openssh.org/[SSH] keys.
endif::dev[]
ifdef::ops[]
* Optimized http://www.postgresql.org/[PostgreSQL] on https://www.freebsd.org/[FreeBSD]. Bulk inserts reduced from hours
to 20 minutes.
* Debugged http://www.python.org/[Python], https://www.freebsd.org/[FreeBSD], http://httpd.apache.org/[Apache], and
https://code.google.com/p/modwsgi/[modwsgi] working together.
endif::ops[]
ifdef::web[]
* Developed multi-threaded back end daemon (in http://www.python.org/[Python]) which connected to the various storage
systems and gathered the data about the stored data for reporting before pushing aggregate data to the billing system.
* Developed web interface that would allow users to drill down and see how storage was being used (by client, by server,
by data center, and/or by storage type).
* Wrote tool to gather performance data from http://www.3par.com/[3Par] InServ nodes and display it via the client
portal.
* Updated and maintained the existing backup monitoring tool which reported backup failures to our main ticketing
system.
* Repackaged http://www.bacula.org/[Bacula] (internal name: SureRestore) for all supported platforms.
* Evaluated potential replacements for https://subversion.apache.org/[Subversion], including
http://www.git-scm.com/[Git] and http://mercurial.selenic.com/[Mercurial].
endif::web[]

[[diversified-systems---systems-administrator-developer]]
Diversified Systems - Systems Administrator / Developer
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Hackettstown, NJ - 2002-2005
ifdef::web[]

Diversified Systems is a small company that focuses on low voltage wiring and subcontracting. While there, I wore many
hats, and did work on every system. The total number of servers for this company was less than 10, and the entire IT
department consisted of myself.

endif::web[]
ifdef::dev[]
* Developed GUI to http://www.ibsoft-us.com/sbn-complete/[new software system] using http://www.php.net/[PHP],
http://httpd.apache.org/[Apache], and http://www.mozilla.org/[Mozilla].
* Automated sending faxes to techs, saving five hours/day (in a 10 person office).
endif::dev[]
ifdef::ops[]
* Deployed http://unattended.sourceforge.net/[Unattended], an automated
http://windows.microsoft.com/en-US/windows/home[Windows] installation system.
* Implemented http://www.hylafax.org/content/Main_Page[HylaFax] fax server for incoming and outgoing faxes, allowing
electronic receipt of over 200 pages of faxes per day from field technicians.
endif::ops[]
ifdef::web[]
* Worked with upper management to completely redesign entire business processes and systems company-wide (accounting,
customer service, builder coordination, sales and warehouse management).
* Modified http://www.sql-ledger.com/[SQL-Ledger] accounts receivable report for historical views of accounts
receivable. The modified version was capable of showing how accounts receivable looked on a given day.
* Implemented employee remote-access system, using VPN (virtual private network).
* Deployed SNMP and monitored daily resource utilization.
* Converted structured portion of data from older system into a database, and provided training to employees on proper
usage.
* Created http://www.php.net/[PHP] scripts to provide clean access to unstructured data from older system, and showed
employees how to access and use.
* Managed upgrade of entire office to http://windows.microsoft.com/en-US/windows/home[Windows] 2000. This involved
testing programs for compatibility, replacing obsolete programs, and determining proper installation procedures for
undocumented installations.
* Resolved issues with the various systems which Diversified Systems installs in customer homes, including alarm
systems, stereos, central vacuums, and structured wiring on a daily basis.
* Coordinated the activities of field technicians with customers to provide the maximum service level to the customers.
* Authored new scripts using https://www.perl.org/[Perl] and http://www.php.net/[PHP].
endif::web[]
ifdef::web[]
[[ciber-inc.-decision-consultants---member-of-technical-staff]]
Ciber, Inc. / Decision Consultants - Member of Technical Staff
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Greenwood Village, Co - 1999-2002

Decision Consultants (DCI) was acquired by Ciber, Inc., in 2002. While working for DCI, I was contracted out to Coors,
IBM, and a .com named "X-Care" (no longer in business). The points below come from all of those places.

* Ran, and later automated, nightly code compilations for patient records program. This effort saved approximately 1000
developer hours per week. Before this effort, corrupted nightly compilations stopped the whole team until resolved
(usually an entire day would be lost). After this effort, no corrupted compilations occurred for over six months.
* Revamped and improved scripts used by developers for retrieving the nightly code compilations and to perform their own
personal compiles, providing new features as requested.
* Wrote several smaller scripts related to the compilation process, to help developers understand what would be required
for their work to be completed.
* Researched/corrected error in https://www.perl.org/[Perl], permitting resolution of time-zone conversion issues,
enabling global use of data from medical care providers.
* Created https://www.perl.org/[Perl] scripts to migrate health care provider data between systems.
* Integrated http://www.ibm.com/systems/power/software/aix/[AIX]/http://www.oracle.com/solaris[Solaris] servers into
http://windows.microsoft.com/en-US/windows/home[Windows] NT network, allowing developers on
http://windows.microsoft.com/en-US/windows/home[Windows] to access
http://www.ibm.com/systems/power/software/aix/[AIX]/http://www.oracle.com/solaris[Solaris] files/printers.
* Developed a set of http://www.oracle.com/solaris[Solaris] packages allowing deployment of new servers within 2 hours
of receipt.
* Developed http://en.wikipedia.org/wiki/Ghost_(software)[Ghost]-like utility overnight, meeting next-morning deadline
for usable computer loads.
* Configured several Sun Ultra servers to work as part of a network. Original condition was such that they were on a
network, but not working together. This involved re-mapping user id numbers, and configuring NFS mounts such that the
machines worked together.
* Configured and administered a http://www.nongnu.org/cvs/[CVS] repository.
* Created a set of http://www.oracle.com/solaris[Solaris] packages to allow the deployment of new
http://www.oracle.com/solaris[Solaris] servers within 2 hours of receiving them.
* Coded many scripts to perform several daily tasks.
* Downloaded and tested new tools to be used for the compilation process, to make sure they still produced correct
results.
* Installed https://www.perl.org/[Perl] modules and programs as requested by developers.
* Documented all new scripts and processes, and informed developers when new documents were available.
* Participated in configuration of training room using http://www.redhat.com/[Red Hat Linux] with
http://en.wikipedia.org/wiki/Kickstart_(Linux)[Kickstart].
* Assisted customers in resolution of issues with http://windows.microsoft.com/en-US/windows/home[Windows] 95,
http://windows.microsoft.com/en-US/windows/home[Windows] NT, Microsoft Office, and other software packages in use
throughout Coors.
* Instructed junior developers in the inner workings of C++.

[[robert-half-international---technical-support]]
Robert Half International - Technical Support
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Boulder, Co - 1999

Robert Half International's client, StorageTek, provided large enterprises with long term backup solutions (typically
involving dozens of tape drives, thousands of tape cartridges, and robotic tape libraries to manage all of it).

* Assisted customers of StorageTek in resolution of problems with both hardware and software products.

[[sykes-enterprises---systems-technologist]]
Sykes Enterprises - Systems Technologist
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Denver, Co - 1998

Working for Sykes Enterprises, I was contracted out to Sun's internal Resolution Center. I worked with Sun employees
around the world to resolve their issues with the workstations and servers they relied on daily.

* Performed remote operating system installations and upgrades.
* Resolved customer issues with http://www.oracle.com/solaris[Solaris] 2.5.1 and http://www.oracle.com/solaris[Solaris]
2.6.
* Wrote a http://www.tcl.tk/[Tcl/Tk] script to speed up the process of logging into customers' machines for use in the
Resolution Center.
* Wrote a Korn shell script to check a list of users and make sure that all users on the list were valid Sun employees.
* Added new users throughout Sun's internal network.

[[fabian-corporation---system-administrator]]
Fabian Corporation - System Administrator
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Strousdburg, Pa - 1998

Fabian Corporation was a small virtual hosting provider for web sites during the fledgling web days, even before the
dot-com era. A typical customer made a static web site and uploaded it via ftp to show to any web site visitors.

* Added new domains to Linux servers for web site hosting.
* Added new user logins to servers.
* Set up sendmail to forward email addresses from hosted domains to local users and remote users.
* Performed system upgrades (both hardware and software).
* Performed system backups.
* Dealt with security issues through upgrades, and removal of suspicious software.
* Installed firewall.
* Upgraded and recompiled kernel as needed.

[[maxtech-corporation---developer-system-administrator]]
MaxTech Corporation - Developer / System Administrator
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Rockaway, NJ - 1995-1997

I was hired at MaxTech as a customer service representative. Over the time I worked there, I earned the opportunity to
participate in system administration and the development of a new call tracking system to be used by the customer
service team.

* Assisted customers daily with issues installing, configuring, and using their MaxTech modems.
* Discovered bug in the newly released modem drivers for http://windows.microsoft.com/en-US/windows/home[Windows] 95 and
the MaxTech 28.8kbps modems.
* Created a new http://windows.microsoft.com/en-US/windows/home[Windows] based call tracking system to replace the old
http://en.wikipedia.org/wiki/MS-DOS[MS-DOS] based call tracking system. Used
http://en.wikipedia.org/wiki/Delphi_(programming_language)[Delphi] and http://en.wikipedia.org/wiki/InterBase[InterBase]
as the development environment and database.
* Rebuilt http://en.wikipedia.org/wiki/NetWare[Novell NetWare] server that had experienced hard drive crash. Did so
while the server was in Atlanta, GA and I was in Rockaway, NJ.
* Fixed issues with the http://en.wikipedia.org/wiki/Cc:Mail[Lotus cc:Mail] SMTP gateway.
* Helped test the new MaxTech website.

[[personal-and-side-projects---developer-systems-administrator]]
Personal and Side Projects - Developer, Systems Administrator
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

1995-Current

When I'm not working on projects for my employer, I'm working on projects for myself, or side projects for people who
get in touch with me to make something for them.

* Studying Android application development at http://www.udacity.com/[Udacity.com].
* Starting in 2009, I began participating in the http://www.turbogears.org/[TurboGears] project, working primarily on
the documentation. In 2011 and 2012, I was the lead project maintainer, and we put out three releases in 2011 alone. As
of now, I still manage the server and DNS for http://www.turbogears.org/[turbogears.org], with work on documentation,
bug fixing, new features, and mailing list management, as time permits.
* Created http://www.java.com/[Java] https://bitbucket.org/pedersen/openfire_vbulletin[plugin] for
http://www.igniterealtime.org/projects/openfire/[Openfire XMPP] server, allowing http://www.vbulletin.com/[vBulletin]
forums to have a working XMPP server for their communities.
* Created Linux-based network featuring NIS, NFS, DHCP, Linux firewall (using iptables), http://www.samba.org/[Samba],
http://www.openssh.org/[SSH], https://subversion.apache.org/[Subversion] server, and
http://mercurial.selenic.com/[Mercurial].
* Customized installation of https://www.bestpractical.com/rt/[Request Tracker] for San Diego firm.
* Contributed patch to http://mercurial.selenic.com/[Mercurial] to assist with repository conversions. Specifically, it
allows branches to be renamed (useful for repositories that used named branches in
https://subversion.apache.org/[Subversion] to change their main trunk location).
* Implemented initial http://en.wikipedia.org/wiki/Pluggable_authentication_module[Pluggable Authentication Module]
support for http://www.hylafax.org/content/Main_Page[HylaFax], which was accepted into
http://www.hylafax.org/content/Main_Page[HylaFax] 4.2.0.
* Contributed code to http://www.mythtv.org/[MythTV] project, allowing users to save recordings using custom cut lists,
which allowed for easy removal of commercials.
* Contributed documentation to http://www.webgui.org/[WebGUI] project, showing how to design a custom theme for
http://www.webgui.org/[WebGUI].
* Contributed documentation to http://www.pqxx.org/[libpqxx] project, showing how to compile
http://www.pqxx.org/[libpqxx] using http://www.mingw.org/[MinGW/MSYS] on
http://windows.microsoft.com/en-US/windows/home[Windows].
* Helped clients, family, and friends resolve various computer and home networking issues.
endif::web[]

<<<

[[specific-skills]]
Specific Skills
---------------

ifdef::dev[]
[[software-configuration-management-tools]]
Software Configuration Management Tools
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[width="100%",cols="64%,^10%,^10%,<16%",options="header",]
|===============================================================
| |Time Used |Last Used |Proficiency
|http://www.git-scm.com/[Git] |2 years |2014 |Fair
|http://mercurial.selenic.com/[Mercurial] |4 years |2014 |Good
|https://subversion.apache.org/[Subversion] |2 years |2010 |Good
|===============================================================

[[markup-languages]]
Markup Languages
~~~~~~~~~~~~~~~~

[width="100%",cols="64%,^10%,^10%,<16%",options="header",]
|===================================
| |Time Used |Last Used |Proficiency
|CSS |2 years |2014 |Fair
|HTML |1 years |2014 |Very Good
|XML |2 years |2011 |Fair
|===================================

[[programming-skills]]
Programming Skills
~~~~~~~~~~~~~~~~~~

[width="100%",cols="64%,^10%,^10%,<16%",options="header",]
|=====================================================
| |Time Used |Last Used |Proficiency
|Object-Oriented Design |8 years |2014 |Very Good
|Object-Oriented Programming |8 years |2014 |Very Good
|Refactoring |4 years |2014 |Very Good
|=====================================================

[[database-skills]]
Database Skills
~~~~~~~~~~~~~~~

[width="100%",cols="64%,^10%,^10%,<16%",options="header",]
|==================================================================================
| |Time Used |Last Used |Proficiency
|http://www.postgresql.org/[PostgreSQL] Database Administration |1 year |2011 |Fair
|Relational Schema Design |5 years |2014 |Very Good
|Structured Query Language (SQL) |12 years |2014 |Very Good
|==================================================================================
endif::dev[]

ifdef::ops[]
[[operating-systems-administered]]
Operating Systems Administered
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[width="100%",cols="<64%,^10%,^10%,<16%",options="header",]
|=======================================================================================================================
| |Time Used |Last Used |Proficiency
|Linux (http://www.debian.org/[Debian], http://www.redhat.com/[RedHat], http://www.suse.com/[Suse],
http://www.ubuntu.com/[Ubuntu]) |12 years |2014 |Excellent
|Microsoft Windows (2008/7/Vista/2003/XP/NT/98/95) |12 years |2011 |Good
|UNIX (http://www.oracle.com/solaris[Solaris], http://www.ibm.com/systems/power/software/aix/[AIX],
http://www8.hp.com/us/en/products/servers/hp-ux.html[HP-UX]) |5 years |2011 |Very Good
|=======================================================================================================================

[[database-servers]]
Database Servers
~~~~~~~~~~~~~~~~

[width="100%",cols="64%,^10%,^10%,<16%",options="header",]
|===========================================================================================================
| |Time Used |Last Used |Proficiency
|http://www.microsoft.com/en-us/server-cloud/products/sql-server/[Microsoft SQL Server] |3 years |2008 |Fair
|http://www.mysql.com/[MySQL] |3 years |2014 |Fair
|http://www.postgresql.org/[PostgreSQL] |5 years |2011 |Fair
|===========================================================================================================

[[applications]]
Applications
~~~~~~~~~~~~

[width="100%",cols="64%,^10%,^10%,<16%",options="header",]
|====================================================================
| |Time Used |Last Used |Proficiency
|http://www.whatsupgold.com/[Ipswitch What's Up] |2 years |2008 |Good
|http://www.nagios.org/[Nagios] |3 years |2012 |Good
|http://www.openstack.org/[OpenStack] |<1 year |2012 |Fair
|http://www.virtualbox.com/[VirtualBox] |3 years |2014 |Good
|http://www.vmware.com/[VMware] |6 years |2011 |Fair
|http://www.zenoss.org/[Zenoss] |<1 year |2011 |Fair
|====================================================================

[[networking-and-security]]
Networking and Security
~~~~~~~~~~~~~~~~~~~~~~~

[width="100%",cols="64%,^10%,^10%,<16%",options="header",]
|===============================================================
| |Time Used |Last Used |Proficiency
|http://www.checkpoint.com/[Checkpoint VPN] |2 years |2007 |Fair
|Cisco |3 years |2011 |Fair
|Firewall Design |5 years |2011 |Good
|TCP/IP |10 years |2014 |Very Good
|===============================================================
endif::ops[]

[[programming-and-scripting-languages]]
Programming and Scripting Languages
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[width="100%",cols="64%,^10%,^10%,<16%",options="header",]
|===============================================================================
| |Time Used |Last Used |Proficiency
|http://www.gnu.org/software/bash/manual/bashref.html[Bash] |6 years |2014 |Good
|C/C++ |12 years |2009 |Good
|http://www.java.com/[Java] |1 year |2014 |Fair
|Javascript |2 years |2014 |Good
|https://www.perl.org/[Perl] |6 years |2012 |Fair
|http://www.php.net/[PHP] |2 years |2012 |Fair
|http://www.python.org/[Python] |6 years |2014 |Excellent
|===============================================================================

[[education]]
Education
~~~~~~~~~

Bachelor of Science in Computer Science, 2000 +
East Stroudsburg University, East Stroudsburg, Pennsylvania

<<<

[[project-history]]
Project History
---------------

ifdef::dev[]
[[advanced-search-tool]]
Advanced Search Tool
~~~~~~~~~~~~~~~~~~~~

[width="86%",cols="<13%,<87%",]
|===========================================================================================================
|*Period* |2014
|*Company* |OrcaTec, LLC
|*Tools* |http://www.python.org/[Python], http://www.jquery.com/[jQuery], http://www.jqueryui.com/[jQueryUI]
|*Platform* |Server: http://www.turbogears.org/[TurboGears], Browser (Cross Browser)
|===========================================================================================================

At OrcaTec, the primary tool we provided to our customers was the ability to search collections of documents quickly. In
addition to having simple search tools, we also had a helper tool in the "Advanced Search".

This tool allowed the user to search based on a dozen different fields, but was still limited and fragile. It was unable
to help the user build queries which combined different fields in a single clause. In addition, it had issues with
encoding <> in email addresses, and did not support drag and drop on all of our supported browsers.

When this project was completed, this tool had transformed noticeably. It now is its own miniature investigative tool,
allowing customers to easily search through collections of documents. One customer reported narrowing their searches
from 80,000 possible documents down to under 2,000 within an hour through use of this tool. Due to extensive test
coverage when the code was published, even the problems that were found were quickly fixable. All of this was
accomplished while reducing the total code for it by 50%.

* Debugged issues with drag/drop on mobile browsers.
* Designed new interface for maximum flexibility, and to allow easy refinement of queries as they are being built.
* Incorporated user feedback to improve that design.

[[storageweb]]
StorageWeb
~~~~~~~~~~

[width="86%",cols="<13%,<87%",]
|=======================================================================================================================
|*Period* |2010

|*Company* |Datapipe

|*Tools* |https://www.freebsd.org/[FreeBSD], http://www.python.org/[Python], http://httpd.apache.org/[Apache],
http://www.postgresql.org/[PostgreSQL], http://www.turbogears.org/[TurboGears]

|*Platform* |https://www.freebsd.org/[FreeBSD], Web Browser
|=======================================================================================================================

Datapipe manages thousands of servers. Many of these servers are connected to various shared storage systems, including
http://www.3par.com/[3Par], http://www.isilon.com/[Isilon], and backup servers. Datapipe required an ability to do
reporting on what data was being stored on these systems for each client, and then report that data back to billing.
StorageWeb was written to fill that need.

* Debugged issues with http://www.python.org/[Python], https://www.freebsd.org/[FreeBSD],
http://httpd.apache.org/[Apache], and https://code.google.com/p/modwsgi/[modwsgi]. Turned out to require specific
compilation options to get these all working correctly.
* Developed web interface that would allow users to drill down and see how the storage was being used (by client, by
server, by data center, by storage type).
* Developed multi-threaded backend daemon which connected to the various storage systems and gathered the data about the
stored data for reporting.
* Developed backend daemon that pushed aggregate data to the billing system, allowing billing to finally happen for all
clients.
endif::dev[]

ifdef::ops[]
[[pasterpaster-to-apacheapachemod_wsgimodwsgi-conversion]]
http://www.pythonpaste.org/[Paster] to http://httpd.apache.org/[Apache]/https://code.google.com/p/modwsgi/[mod_wsgi] Conversion
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[width="86%",cols="<13%,<87%",]
|=======================================================================================================================
|*Period* |2013

|*Company* |OrcaTec, LLC

|*Tools* |http://www.python.org/[Python], http://httpd.apache.org/[Apache],
https://code.google.com/p/modwsgi/[mod_wsgi], http://www.pythonpaste.org/[Paster]

|*Platform* |http://www.ubuntu.com/[Ubuntu] Linux
|=======================================================================================================================

http://www.pythonpaste.org/[Paster] is meant to be used in a development environment, allowing the developer to use a
(single threaded) lightweight, easily managed webserver while writing code before it goes to production. At OrcaTec, we
were using http://www.pythonpaste.org/[Paster] both in development and in production. Due to the demands being placed on
http://www.pythonpaste.org/[Paster] (in many instances, loading up documents that were over 100M), the entire system
could appear (to one user) to freeze up due to it responding to a request from another user.

After analysis, we were able to determine that http://www.pythonpaste.org/[Paster] was no longer suitable for our needs.
Since http://httpd.apache.org/[Apache], with https://code.google.com/p/modwsgi/[mod_wsgi], provides an at least adequate
performance web server (in comparison to others like Nginx), and the http://httpd.apache.org/[Apache] configuration was
already known to the team, we chose to switch from http://www.pythonpaste.org/[Paster] to
http://httpd.apache.org/[Apache]. This allowed us to have http://httpd.apache.org/[Apache] itself serve up static files
(like images, css files, and javascript files), leaving the dynamic pages to the http://www.python.org/[Python] code.

* Debugged threading/locking/memory usage issues with http://www.pythonpaste.org/[Paster].
* Recompiled and repackaged http://www.python.org/[Python 2.6.8], http://httpd.apache.org/[Apache], and
https://code.google.com/p/modwsgi/[mod_wsgi] for use with http://www.ubuntu.com/[Ubuntu 10.04].
* Developed automatic http://httpd.apache.org/[Apache] configuration for use within our local stack.

[[sapsap-to-tylertyler-conversion]]
http://www.sap.com/[SAP] to http://www.tylernet.com/[Tyler] Conversion
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[width="86%",cols="<13%,<87%",]
|=======================================================================================================================
|*Period* |2011

|*Company* |6th Avenue Electronics

|*Tools* |https://www.autoitscript.com/site/autoit/[AutoIt3], http://www.centos.org/[CentOS] Linux,
http://www.python.org/[Python]

|*Platform* |Server: http://www.centos.org/[CentOS] Linux, Client:
http://windows.microsoft.com/en-US/windows/home[Windows]
|=======================================================================================================================

6th Avenue Electronics found that http://www.sap.com/[SAP] was not a workable solution for them. The decision was made
to switch back to the http://www.tylernet.com/[Tyler] POS system, clearing out old mistakes and improving
maintainability. I managed the technical aspects of the migration, while my immediate managers handled the business
aspects.

Due to the costs associated with http://www.sap.com/[SAP], we had just over three months, in total, to complete the
transition. We were successful.

* Wrote several one-off scripts to check data that was sent in various Excel spreadsheets. Validate that all entries in
column A of File 1/Sheet 1 are in Column C of File 2/Sheet 1.
* Used https://www.autoitscript.com/site/autoit/[AutoIt3] to automate the update of several items that could only be
keyed into the client. No import existed at all. This reduced work from several hours down to an hour (including the
initial script creation).
* Developed an automated installer that was used to handle installing all components (receipt printer, fonts, initial
configuration) on every machine in the company.
* Worked with http://www.tylernet.com/[Tyler] Retail Systems to configure the server properly.
* Developed snapshot backup strategy that reduces downtime for http://www.tylernet.com/[Tyler] to mere minutes per
night.
endif::ops[]

ifdef::web[]
[[unixops]]
UNIXOps
~~~~~~~

[width="86%",cols="<13%,<87%",]
|=======================================================================================================================
|*Period* |2010

|*Company* |Datapipe

|*Tools* |https://www.freebsd.org/[FreeBSD], http://www.python.org/[Python], http://httpd.apache.org/[Apache],
http://www.php.net/[PHP]

|*Platform* |https://www.freebsd.org/[FreeBSD], Web Browser
|=======================================================================================================================

Datapipe provides managed hosting for its clients. This means that customers contact Datapipe to report issues on
servers, and Datapipe administrators log in to customer machines as root to fix the problems. UNIXOps provides a secure
method to allow the administrators a one time SSH key to login to the customer equipment, along with providing detailed
logging of everything the administrator does for later review.

* Installed and configured client-side SSL certificate validation for Apache, requiring that machines connecting to
UNIXOps provide a valid SSL certificate before being granted any access.
* Developed the code that would follow the workflow of Datapipe: Administrator requests access, UNIXOps configures the
access on the client machine, administrator uses that access, and the access is revoked when used or 15 minutes have
passed without it being used.

[[pytyler---tylertyler-pos-to-postgresqlpg-migration-tool]]
PyTyler - http://www.tylernet.com/[Tyler] POS to http://www.postgresql.org/[PostgreSQL] Migration Tool
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[width="86%",cols="<13%,<87%",]
|=======================================================================================================================
|*Period* |2007, 2011

|*Company* |6th Avenue Electronics

|*Tools* |http://www.python.org/[Python], http://www.postgresql.org/[PostgreSQL], http://www.tylernet.com/[Tyler] POS
System

|*Platform* |http://www8.hp.com/us/en/products/servers/hp-ux.html[HP-UX], http://www.debian.org/[Debian] GNU/Linux
|=======================================================================================================================

http://www.tylernet.com/[Tyler] is a point of sale system used by many smaller retail establishments.
http://www.tylernet.com/[Tyler] stores data in a set of proprietary ISAM files. These files do not have a modern access
tool available (such as Crystal Reports) to perform reporting.

The users needed an easy way to report on the data, and this meant a tool was needed to copy the data from the on-disk
files into a formal SQL server of some variety. In less than a month, I wrote a tool in http://www.python.org/[Python]
to read the http://www.tylernet.com/[Tyler] data files and load the information into a
http://www.postgresql.org/[PostgreSQL] database on a nightly basis.

This tool copied the entire database, comprising approximately 36,000,000 records, 140 tables, and 22 gigabytes of disk
space. The program worked by reading the structure definition from the configuration files and recreating the structure
in http://www.postgresql.org/[PostgreSQL]. PyTyler would then read each table, row by row, parse the data in the row,
and load it into http://www.postgresql.org/[PostgreSQL] server.

This allowed the users to use standard ODBC drivers to access and report on the data.

* Developed a tool to read configuration of ISAM files, and generate SQL "create table" statements mirroring the
structure of the file.
* Created a specialized reader class which could read the data stored in the ISAM table.
* Developed small web server application to provide status page for administrators while migration tool runs
* Reduced total run time from 13 hours to 5 hours by converting the entire application into a multi-threaded
application.
* Verified that data is being copied into the system correctly.
* http://www.tylernet.com/[Tyler] POS system was in production until the closure of the company in December, 2011, so
data copy ran every night to bring in updated data from previous day's activities.

[[vmwarevmware-implementation]]
http://www.vmware.com/[VMware] Implementation
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[width="86%",cols="<13%,<87%",]
|===============================================================================================================
|*Period* |2005-2007
|*Company* |6th Avenue Electronics
|*Tools* |http://www.vmware.com/[VMware] Virtual Infrastructure 3, http://www.vmware.com/[VMware] Virtual Center
|*Platform* |Linux (Various distributions), http://windows.microsoft.com/en-US/windows/home[Windows] Server 2003
|===============================================================================================================

6th Avenue Electronics, like many companies, had a growing need for individual servers for various internal services.
They chose to implement http://www.vmware.com/[VMware] to reduce hardware costs, downtime, and environmental costs.

* Installed and configured iSCSI based SAN disks.
* Installed and configured all aspects of http://www.vmware.com/[VMware] Virtual Center and
http://www.vmware.com/[VMware] Virtual Infrastructure 3.
* Developed (and tested) virtual machine templates to allow rapid deployment of new virtual servers using various
operating systems (http://windows.microsoft.com/en-US/windows/home[Windows] XP,
http://windows.microsoft.com/en-US/windows/home[Windows] 2003, http://www.debian.org/[Debian] GNU/Linux,
http://www.redhat.com/[RedHat] Linux).
* Monitored daily usage of http://www.vmware.com/[VMware] hosts.

[[sbnsbn-implementation]]
http://www.ibsoft-us.com/sbn-complete/[SBN] Implementation
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[width="86%",cols="<13%,<87%",]
|=======================================================================================================================
|*Period* |2004-2005

|*Company* |Diversified Systems

|*Tools* |http://www.ibsoft-us.com/sbn-complete/[SBN], http://www.sybase.com/[Sybase 11.0], http://www.php.net/[PHP]

|*Platform* |Microsoft http://windows.microsoft.com/en-US/windows/home[Windows] 2000, http://www.debian.org/[Debian]
GNU/Linux
|=======================================================================================================================

http://www.ibsoft-us.com/sbn-complete/[SBN], published by IBSoft, is an ERP system for the alarm industry. Diversified
Systems is a subcontractor working in the low voltage electrical industry, including alarm systems, stereo systems,
central intercom systems, structured wiring, and central vacuum systems. I implemented all aspects of
http://www.ibsoft-us.com/sbn-complete/[SBN] at Diversified Systems.

The provided client interface was unsuited for the intended use. This resulted in much in-house development to augment
the http://www.ibsoft-us.com/sbn-complete/[SBN] client with a web-based interface.

* Configured all aspects of http://www.ibsoft-us.com/sbn-complete/[SBN] from base installation to full production mode,
with active communication with users at each step.
* Implemented over 50 custom screens and reports using http://www.php.net/[PHP] on an http://httpd.apache.org/[Apache]
web server. This included easier access to customer searches, more usable technician schedules, and easier input for
large quantities of data.
* Developed automated system for the sending of faxes to field technicians,saving over 5 work hours per day.
* Implemented an automated backup system for the database.
* Administered http://www.sybase.com/[Sybase] instance on day to day basis, resolving issues with full log files, etc.

[[sql-ledgersqlledger-implementation]]
http://www.sql-ledger.com/[SQL-Ledger] Implementation
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[width="86%",cols="<13%,<87%",]
|======================================================================================
|*Period* |2005
|*Company* |Diversified Systems
|*Tools* |https://www.perl.org/[Perl], http://httpd.apache.org/[Apache]
|*Platform* |http://httpd.apache.org/[Apache], http://www.debian.org/[Debian] GNU/Linux
|======================================================================================

The http://www.ibsoft-us.com/sbn-complete/[SBN] accounting system was inadequate for the needs of Diversified Systems.
This lead to the selection and installation of an external accounting package.

* Authored script to automatically migrate necessary data (customers, bills to be collected, etc.) from
http://www.ibsoft-us.com/sbn-complete/[SBN] to http://www.sql-ledger.com/[SQL-Ledger].
* Installed and configured http://www.sql-ledger.com/[SQL-Ledger].

[[kp-cis]]
KP-CIS
~~~~~~

[width="87%",cols="<14%,<86%",]
|=======================================================================================================================
|*Period* |2001-2002

|*Company* |Ciber, Inc., contracted to IBM

|*Tools* |https://www.perl.org/[Perl], https://www.cygwin.com/[Cygwin], http://www.gnu.org/software/make/[GNU Make]

|*Platform* |Server: http://www.ibm.com/systems/power/software/aix/[AIX], Client:
http://windows.microsoft.com/en-US/windows/home[Windows] NT
|=======================================================================================================================

IBM was under contract to develop a complete clinical information system for Kaiser Permanente clinics. I participated
as a member of the environment team, focusing on improving the build processes.

* Resolved issues with corrupted builds occurring weekly, resulting in savings of over 1000 work hours every week.
* Developed and improved approximately 450 compilation scripts and Makefiles on
http://www.ibm.com/systems/power/software/aix/[AIX] and http://windows.microsoft.com/en-US/windows/home[Windows]
NT/2000, fixing dependency issues and allowing reliable use of nightly code compilations.
* Evaluated, tested, integrated, and deployed new compilation tools.
endif::web[]
